### ISSUE TITLE
Fix instructions to work with Swift 3.0.2

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/speech-to-text-swift#1]
Attempting to follow the instructions with Swift 3.0.2 results in the error: "module compiled with swift 3.0 cannot be imported in swift 3.0.2".

A more robust (though slower) instruction example is: `carthage update --platform iOS --no-use-binaries`

**Comment by schen22** [comment]
Thanks @jsstylos for pointing that out! Updated the README with your suggestion.
