### ISSUE TITLE
With the current SDK the code is not working 

### ISSUE THREAD

**Issue by foward** [watson-developer-cloud/speech-to-text-swift#14]
I have several errors just using the code as-is, with the current version of Watson-SDK ...could you please check ? Thanks

**Comment by foward** [comment]
Fixed using and replacing those lines...

<img width="809" alt="screen shot 2018-05-28 at 12 59 40" src="https://user-images.githubusercontent.com/249026/40623841-0ce21cea-6277-11e8-9241-aa652d53fe9a.png">
<img width="789" alt="screen shot 2018-05-28 at 12 59 35" src="https://user-images.githubusercontent.com/249026/40623842-0d099572-6277-11e8-8fb9-fa52c29b7e87.png">
<img width="802" alt="screen shot 2018-05-28 at 12 59 27" src="https://user-images.githubusercontent.com/249026/40623843-0d2f3fb6-6277-11e8-889b-62770a7ef901.png">

**Comment by germanattanasio** [comment]
It looks like you know what to change @foward. 
Do you mind creating a PR?

**Comment by foward** [comment]
sure but I don't have access to do it :) , I have the commit already waiting ... :)

**Comment by germanattanasio** [comment]
If you forked the repo, you have a copy of this in your namespace which is where you probably did the change. In order to merge that change with this repo, you need to create a PR. 

Here are the steps https://help.github.com/articles/creating-a-pull-request/

**Comment by foward** [comment]
PR done ...just waiting for approval 👍 Thanks

**Comment by germanattanasio** [comment]
Thanks @foward I've asked @mkistler to look at it https://github.com/watson-developer-cloud/speech-to-text-swift/pull/15
