### ISSUE TITLE
recognizeMicrophone does not work on Xcode 10.1 iOS 12 swift-sdk 1.1.0

### ISSUE THREAD

**Issue by maggix** [watson-developer-cloud/speech-to-text-swift#18]
Using the provided sample as of 18-12-2018, following the tutorial on swift-sdk 1.1.0, Xcode 10.1 and iOS SDK 12.1 results in:

`Incorrect argument label in call (have 'settings:failure:_:', expected 'settings:model:completionHandler:')`

on line: `            speechToText.recognizeMicrophone(settings: settings, failure: failure) {`

**Comment by germanattanasio** [comment]
Last time this demo was updated was July 2nd and we just released the swift-sdk v1.0 so I think this demo is just outdated. @maggix Would you like to write a patch for this? I'd be more than happy to walk you through the steps involved.

**Comment by maggix** [comment]
Hi @germanattanasio , thank you for your reply. I started working on it on a fork 
https://github.com/maggix/speech-to-text-swift , will submit a pull request as soon as I get to test it.
