### ISSUE TITLE
Error when using Swift 3.0.2

### ISSUE THREAD

**Issue by niblic99** [watson-developer-cloud/speech-to-text-swift#2]
I downloaded the Project and followed the instructions.
I had to use 
carthage update --platform iOS  --no-use-binary

since the libs are compiled with Swift 3.0 and are not matching.

I use Swift 3.0.2 and the code is producing an error when running.

keyNotFound("voices")

Error Domain=com.ibm.watson.developer-cloud.TextToSpeechV1 Code=0 "Returned audio is in an unexpected format." UserInfo={NSLocalizedFailureReason=Returned audio is in an unexpected format.} 

Solutions of either updating the binaries provided to precompile the project with swift 3.0.2 , and/or whether multiple versions of swift can be installed into xcode.

**Comment by schen22** [comment]
The error was being returned due to invalid credentials. The error description returned is unhelpful however, and we will create an issue to modify error checking within the SDK.
