### ISSUE TITLE
Missing required modules: 'SSCZLib', 'SSCommonCrypto'

### ISSUE THREAD

**Issue by agmo-ios** [watson-developer-cloud/speech-to-text-swift#8]
I can't build the sample project using XCode 9.0.1
Please assist

<img width="745" alt="screen shot 2017-10-31 at 6 27 58 pm" src="https://user-images.githubusercontent.com/23096469/32219483-5312eeb8-be69-11e7-9c3c-d5078a0b7355.png">

**Comment by glennrfisher** [comment]
Hi @agmo-ios. I'm afraid I don't see the same behavior. Could you try a fresh download and see if you run into the same problem? Here's what I just did to check and it ran alright.

1. Download `master` branch.
2. Run `carthage update --platform iOS`
3. Rename `CredentialsExample.swift` to `Credentials.swift`
4. Open `Speech to Text.xcodeproj` and Build / Run.

**Comment by agmo-ios** [comment]
Hi @glennrfisher 

Thanks for your feedback.
When I am using XCode 9.0.1, the carthage update output is as the following:
<img width="846" alt="screen shot 2017-11-02 at 1 00 59 pm" src="https://user-images.githubusercontent.com/23096469/32310526-e7f7f22a-bfcd-11e7-84a1-9798a75549bc.png">

When I am using XCode 9 via xcode-select, the carthage update output is as the following: (It shows some warning but I have no problem in building)
<img width="939" alt="screen shot 2017-11-02 at 1 05 54 pm" src="https://user-images.githubusercontent.com/23096469/32310643-d611e7a4-bfce-11e7-947e-47fe843bd776.png">

Conclusion: It works on XCode 9, but not XCode 9.0.1 (If it works on your side, maybe your xcode-select is still pointing to XCode 9 instead of 9.0.1?)
Buy me a Starbucks please :)

**Comment by agmo-ios** [comment]
A better way is to use "carthage update --platform iOS --no-use-binaries"
Thanks.
